"use strict";

// Turning the knowledge graph into something you can hand to Claude.
//
// The bundle is a directory, not a blob: drop it beside a repo (or point a
// skill at it) and an agent has the architecture, the API contract, the data
// model, the screen wiring and the recent history in the form each one reads
// best — prose where prose helps, JSON where the agent needs to look things up.

const fs = require("node:fs");
const path = require("node:path");
const { db } = require("../db");
const { config } = require("../config");
const { readKnowledgeGraph } = require("./knowledge");

const BUNDLE_VERSION = 1;

/** A YAML double-quoted scalar, safe for arbitrary prose. */
function yamlScalar(text) {
  return `"${String(text).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function slug(s) {
  return String(s || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") || "unnamed";
}

function bullets(items, prefix = "- ") {
  return (items || []).filter(Boolean).map((i) => `${prefix}${i}`).join("\n");
}

/**
 * One table cell, safe for arbitrary model- and repository-derived text.
 *
 * A pipe inside a TypeScript union (`string | null` — extremely common in a
 * field type) closes the column early, so every row after it in the table is
 * mis-aligned and the document an agent reads becomes unparseable nonsense
 * exactly where the type information is.
 */
function cell(text) {
  return String(text ?? "")
    .replace(/\|/g, "\\|")
    .replace(/\r?\n/g, " ")
    .trim();
}

/** Repository text inside a code span. A backtick in it would close the span. */
function code(text) {
  return String(text ?? "").replace(/`/g, "'");
}

function fieldTable(fields) {
  if (!fields || fields.length === 0) return "_none declared in source_";
  const rows = fields.map(
    (f) => `| \`${code(f.name)}\` | ${cell(f.type) || "?"} | ${f.required ? "yes" : "no"} | ${cell(f.note)} |`,
  );
  return ["| Field | Type | Required | Notes |", "| --- | --- | --- | --- |", ...rows].join("\n");
}

// ── the document an agent reads first ────────────────────────────────────────

function renderClaudeMd(kg) {
  const o = kg.overview || {};
  const cmd = o.commands || {};
  const out = [];

  out.push(`# ${kg.repo.name}`);
  out.push("");
  out.push(o.elevatorPitch || o.purpose || "");
  out.push("");
  out.push(
    `> Generated by RepoDeck from \`${kg.repo.branch}\` at \`${(kg.repo.indexedSha || "").slice(0, 12)}\`` +
      `${kg.repo.builtAt ? ` on ${kg.repo.builtAt} UTC` : ""}. Regenerated on every pull, so treat it as current.`,
  );
  out.push("");

  if (o.purpose) {
    out.push("## What this is");
    out.push("");
    out.push(o.purpose);
    out.push("");
  }

  if (o.architecture) {
    out.push("## Architecture");
    out.push("");
    out.push(o.architecture);
    out.push("");
  }

  if (o.stack && o.stack.length) {
    out.push("## Stack");
    out.push("");
    out.push(bullets(o.stack.map((s) => `**${s.name}**${s.version ? ` ${s.version}` : ""} — ${s.role}`)));
    out.push("");
  }

  if (o.entryPoints && o.entryPoints.length) {
    out.push("## Where execution starts");
    out.push("");
    out.push(bullets(o.entryPoints.map((e) => `\`${e.path}\` — ${e.what}`)));
    out.push("");
  }

  const commandRows = Object.entries(cmd).filter(([, v]) => v);
  if (commandRows.length) {
    out.push("## Commands");
    out.push("");
    out.push("```bash");
    for (const [k, v] of commandRows) out.push(`# ${k}\n${v}`);
    out.push("```");
    out.push("");
  }

  if (kg.env.length) {
    const required = kg.env.filter((v) => v.required);
    out.push("## Configuration");
    out.push("");
    out.push(
      `${kg.env.length} environment variables are read by this codebase` +
        (required.length ? `, ${required.length} of them declared in the example env file` : "") +
        ". Full list with call sites in `knowledge-graph.json`.",
    );
    out.push("");
    if (required.length) {
      out.push(bullets(required.slice(0, 25).map((v) => `\`${v.name}\`${v.example ? ` = ${v.example}` : ""}`)));
      out.push("");
    }
  }

  if (kg.modules.length) {
    out.push("## Modules");
    out.push("");
    out.push(
      "Each module has its own brief in `modules/`. An agent working on a feature should read that file before touching code.",
    );
    out.push("");
    for (const m of kg.modules) {
      out.push(`### ${m.module} (${m.fileCount} files)`);
      out.push("");
      out.push(m.what || "");
      if (m.keyFiles && m.keyFiles.length) {
        out.push("");
        out.push(bullets(m.keyFiles.slice(0, 5).map((f) => `\`${f.path}\` — ${f.why}`)));
      }
      out.push("");
    }
  }

  if (kg.endpoints.length) {
    out.push("## API surface");
    out.push("");
    out.push(`${kg.endpoints.length} endpoints. Full request and response shapes in \`api-surface.md\`.`);
    out.push("");
    out.push("| Method | Path | Handler | Auth |");
    out.push("| --- | --- | --- | --- |");
    for (const e of kg.endpoints.slice(0, 60)) {
      out.push(`| ${e.method} | \`${e.path}\` | \`${e.handler || "?"}\` | ${e.auth || "—"} |`);
    }
    if (kg.endpoints.length > 60) out.push(`| … | _${kg.endpoints.length - 60} more in api-surface.md_ | | |`);
    out.push("");
  }

  if (kg.screens.length) {
    out.push("## Screens");
    out.push("");
    out.push("Which page is connected to what — full detail in `screens.md`.");
    out.push("");
    for (const s of kg.screens.slice(0, 30)) {
      const calls = (s.calls || []).slice(0, 6).map((c) => `\`${c}\``).join(", ");
      out.push(`- **${s.name}**${s.route ? ` (\`${s.route}\`)` : ""} — ${s.summary || ""}${calls ? ` Calls: ${calls}` : ""}`);
    }
    out.push("");
  }

  if (kg.entities.length) {
    out.push("## Data model");
    out.push("");
    // CLAUDE.md is loaded into every agent's context, so it is capped like every
    // other section here; data-model.md carries the full list.
    out.push(
      bullets(
        kg.entities
          .slice(0, 40)
          .map((e) => `**${e.name}**${e.store ? ` (\`${code(e.store)}\`)` : ""} — ${cell(e.summary)}`),
      ),
    );
    if (kg.entities.length > 40) {
      out.push("", `_…and ${kg.entities.length - 40} more — see \`data-model.md\`._`);
    }
    out.push("");
    out.push("Field-level detail in `data-model.md`.");
    out.push("");
  }

  if (o.conventions && o.conventions.length) {
    out.push("## Conventions to follow");
    out.push("");
    out.push(bullets(o.conventions));
    out.push("");
  }

  if (o.gotchas && o.gotchas.length) {
    out.push("## Gotchas");
    out.push("");
    out.push(bullets(o.gotchas));
    out.push("");
  }

  if (kg.hotspots.length) {
    out.push("## Where the work is happening");
    out.push("");
    out.push("Files with the most recent merge activity — the parts of the codebase most likely to be mid-change.");
    out.push("");
    out.push(
      bullets(
        kg.hotspots
          .slice(0, 15)
          // readKnowledgeGraph aliases commit_count to `merges`; reading the raw
          // column name here printed "undefined merges" in every exported CLAUDE.md.
          .map((h) => `\`${h.path}\` — ${h.role || h.layer} (${h.merges ?? 0} merges, ${h.churn} lines)`),
      ),
    );
    out.push("");
  }

  if (kg.flows && kg.flows.length) {
    const endpoints = kg.flows.filter((f) => /\s\//.test(f.key));
    out.push("## How a request moves");
    out.push("");
    out.push(
      `${kg.flows.length} entry points traced from the call graph — every hop below is a real call ` +
        "on a real line. Full detail, including the branches not shown, in `flows.md`.",
    );
    out.push("");
    for (const flow of (endpoints.length ? endpoints : kg.flows).slice(0, 12)) {
      const chain = flow.steps.map((st) => `${st.name}() \`${st.path}:${st.line}\``).join(" → ");
      out.push(`- **\`${flow.key}\`** \`${flow.entryPath}:${flow.entryLine}\`${chain ? ` → ${chain}` : " — does its work inline"}`);
    }
    out.push("");
  }

  if (kg.playbooks && kg.playbooks.length) {
    const total = kg.playbooks.reduce((n, p) => n + (p.playbooks || []).length, 0);
    out.push("## When something breaks");
    out.push("");
    out.push(
      `${total} playbooks across ${kg.playbooks.length} modules, each keyed by the symptom you would ` +
        "actually see. Full text in `playbooks.md`.",
    );
    out.push("");
    for (const module of kg.playbooks.slice(0, 6)) {
      const entries = (module.playbooks || []).slice(0, 3);
      if (entries.length === 0) continue;
      out.push(`**${module.module || module.key}**`);
      out.push("");
      out.push(bullets(entries.map((e) => `${e.symptom} → ${(e.checkFirst || [])[0]?.path || "see playbooks.md"}`)));
      out.push("");
    }

    const invariants = kg.playbooks.flatMap((m) => (m.invariants || []).map((i) => `${m.module || m.key}: ${i}`));
    if (invariants.length) {
      out.push("### Invariants");
      out.push("");
      out.push("Breaking one of these breaks the system even if the tests pass.");
      out.push("");
      out.push(bullets(invariants.slice(0, 20)));
      out.push("");
    }
  }

  if (kg.errors && kg.errors.length) {
    out.push("## Errors this code can raise");
    out.push("");
    out.push(
      `${kg.errors.length} catalogued, each with the line that raises it. Look one up in \`errors.md\` ` +
        "before guessing at a cause.",
    );
    out.push("");
    for (const e of kg.errors.slice(0, 15)) {
      out.push(`- \`${code(e.label)}\` — \`${code(e.path)}:${e.line}\`${e.meaning ? ` · ${cell(e.meaning)}` : ""}`);
    }
    out.push("");
  }

  const describedFunctions = (kg.functions || []).filter((f) => f.purpose);
  if (describedFunctions.length) {
    out.push("## Key functions");
    out.push("");
    out.push(`${describedFunctions.length} functions have a written contract in \`functions.md\`. The most connected:`);
    out.push("");
    for (const fn of describedFunctions.slice(0, 15)) {
      const effects = (fn.sideEffects || []).length ? ` _(${fn.sideEffects[0]})_` : "";
      out.push(`- \`${fn.name}()\` \`${fn.location}\` — ${fn.purpose}${effects}`);
    }
    out.push("");
  }

  if (kg.tests && kg.tests.length) {
    out.push("## Tests");
    out.push("");
    out.push(`${kg.tests.length} source files have tests covering them; the map is in \`tests.md\`.`);
    out.push("");
  }

  if (kg.changelog.length) {
    const latest = kg.changelog[0];
    out.push("## Most recent change");
    out.push("");
    out.push(`**${latest.headline}**`);
    out.push("");
    if (latest.agentImpact && latest.agentImpact.length) {
      out.push("What to unlearn from an older copy of this document:");
      out.push("");
      out.push(bullets(latest.agentImpact));
      out.push("");
    }
    out.push("Full history in `CHANGELOG.md`.");
    out.push("");
  }

  if (o.glossary && o.glossary.length) {
    out.push("## Glossary");
    out.push("");
    out.push(bullets(o.glossary.map((g) => `**${g.term}** — ${g.meaning}`)));
    out.push("");
  }

  return out.join("\n");
}

function renderApiSurface(kg) {
  const out = [`# API surface — ${kg.repo.name}`, ""];
  if (kg.endpoints.length === 0) {
    out.push("_No endpoints were found in this repository._");
    return out.join("\n");
  }

  const byModule = new Map();
  for (const e of kg.endpoints) {
    const key = e.module || "unassigned";
    if (!byModule.has(key)) byModule.set(key, []);
    byModule.get(key).push(e);
  }

  for (const [module, endpoints] of byModule) {
    out.push(`## ${module}`, "");
    for (const e of endpoints) {
      out.push(`### \`${e.method} ${e.path}\``, "");
      if (e.summary) out.push(e.summary, "");
      out.push(
        `- Handler: \`${e.handler || "?"}\`${e.symbol ? ` → \`${e.symbol}()\`` : ""}`,
        `- Auth: ${e.auth || "not stated in source"}`,
      );
      if (e.middleware && e.middleware.length) out.push(`- Middleware: ${e.middleware.map((m) => `\`${m}\``).join(" → ")}`);
      if (e.statusCodes && e.statusCodes.length) out.push(`- Status codes: ${e.statusCodes.join(", ")}`);
      out.push("");

      const req = e.request || {};
      if ((req.pathParams || []).length) out.push("**Path parameters**", "", fieldTable(req.pathParams), "");
      if ((req.queryParams || []).length) out.push("**Query parameters**", "", fieldTable(req.queryParams), "");
      if ((req.bodyFields || []).length) out.push("**Request body**", "", fieldTable(req.bodyFields), "");

      const res = e.response || {};
      if (res.success) out.push("**Response**", "", "```", res.success, "```", "");
      if ((res.errors || []).length) out.push("**Errors**", "", bullets(res.errors), "");
      if (e.evidence) out.push(`_Proven by:_ \`${e.evidence.replace(/`/g, "'")}\``, "");
    }
  }
  return out.join("\n");
}

function renderDataModel(kg) {
  const out = [`# Data model — ${kg.repo.name}`, ""];
  if (kg.entities.length === 0) return out.concat("_No data models were found._").join("\n");

  for (const e of kg.entities) {
    out.push(`## ${e.name}`, "");
    if (e.summary) out.push(e.summary, "");
    if (e.filePath) out.push(`Declared in \`${e.filePath}\`${e.store ? `, stored as \`${e.store}\`` : ""}.`, "");
    out.push(fieldTable(e.fields), "");
    if ((e.relations || []).length) {
      out.push("**Relations**", "");
      out.push(bullets(e.relations.map((r) => `${r.kind} \`${r.to}\`${r.via ? ` via \`${r.via}\`` : ""}`)), "");
    }
  }
  return out.join("\n");
}

function renderScreens(kg) {
  const out = [`# Screens — ${kg.repo.name}`, ""];
  if (kg.screens.length === 0) return out.concat("_No screens were found._").join("\n");

  for (const s of kg.screens) {
    out.push(`## ${s.name}${s.route ? ` — \`${s.route}\`` : ""}`, "");
    if (s.summary) out.push(s.summary, "");
    if (s.filePath) out.push(`File: \`${s.filePath}\``, "");
    if ((s.components || []).length) out.push("**Composes**", "", bullets(s.components.map((c) => `\`${c}\``)), "");
    if ((s.calls || []).length) out.push("**Calls**", "", bullets(s.calls.map((c) => `\`${c}\``)), "");
  }
  return out.join("\n");
}

function renderModule(m) {
  const out = [`# Module: ${m.module}`, "", m.what || "", ""];
  const section = (title, items, fmt = (i) => i) => {
    if (!items || items.length === 0) return;
    out.push(`## ${title}`, "", bullets(items.map(fmt)), "");
  };
  section("Responsibilities", m.responsibilities);
  section("Key files", m.keyFiles, (f) => `\`${f.path}\` — ${f.why}`);
  section("What comes in", m.dataIn);
  section("What goes out", m.dataOut);
  section("Where to extend", m.extendHere);
  section("Risks when changing this", m.risks);
  return out.join("\n");
}

function renderChangelog(kg) {
  const out = [`# Change history — ${kg.repo.name}`, ""];
  if (kg.changelog.length === 0) return out.concat("_No indexed changes yet._").join("\n");

  for (const c of kg.changelog) {
    out.push(`## ${c.headline}`, "", `_${c.updatedAt} UTC${c.toSha ? ` · \`${String(c.toSha).slice(0, 12)}\`` : ""}_`, "");
    if ((c.changes || []).length) {
      out.push(
        bullets(
          c.changes.map((x) => `${x.breaking ? "**BREAKING** " : ""}${x.what} — \`${x.where}\`${x.why ? ` (${x.why})` : ""}`),
        ),
        "",
      );
    }
    if ((c.agentImpact || []).length) out.push("**Agent impact**", "", bullets(c.agentImpact), "");
    if ((c.commits || []).length) {
      out.push("<details><summary>Merges</summary>", "");
      out.push(bullets(c.commits.map((m) => `\`${m.sha}\` ${m.subject}`)), "");
      out.push("</details>", "");
    }
  }
  return out.join("\n");
}

/**
 * A ready-to-drop-in Claude Code subagent per module. These are the reason the
 * graph is worth exporting: each one carries the module's brief as its system
 * prompt, so the agent starts knowing where it is.
 */
function renderAgent(kg, m) {
  const endpoints = kg.endpoints.filter((e) => e.module === m.module);
  const front = [
    "---",
    `name: ${slug(kg.repo.name)}-${slug(m.module)}`,
    // Quoted and escaped: an unquoted YAML scalar containing ": " or a leading
    // "#" makes the whole agent file unparseable, and this text is model prose.
    `description: ${yamlScalar(`Works on the ${m.module} module of ${kg.repo.name}. ${(m.what || "").replace(/\s+/g, " ").slice(0, 160)}`)}`,
    "tools: Read, Edit, Write, Grep, Glob, Bash",
    "---",
    "",
  ].join("\n");

  const body = [
    `You work on the **${m.module}** module of \`${kg.repo.name}\`.`,
    "",
    m.what || "",
    "",
    "## What this module owns",
    "",
    bullets(m.responsibilities),
    "",
    "## Read these first",
    "",
    bullets((m.keyFiles || []).map((f) => `\`${f.path}\` — ${f.why}`)),
    "",
  ];

  if (endpoints.length) {
    body.push("## Endpoints this module serves", "");
    body.push(bullets(endpoints.map((e) => `\`${e.method} ${e.path}\` → \`${e.handler}\` — ${e.summary || ""}`)));
    body.push("");
  }

  if ((m.extendHere || []).length) body.push("## Where to add new capability", "", bullets(m.extendHere), "");
  if ((m.risks || []).length) body.push("## Do not break", "", bullets(m.risks), "");

  const flows = (kg.flows || []).filter((f) => f.module === m.module);
  if (flows.length) {
    body.push("## Traced paths through this module", "");
    for (const flow of flows.slice(0, 8)) {
      const chain = flow.steps.map((st) => `${st.name}() ${st.path}:${st.line}`).join(" → ");
      body.push(`- \`${flow.key}\` (${flow.entryPath}:${flow.entryLine})${chain ? ` → ${chain}` : ""}`);
    }
    body.push("");
  }

  const playbook = (kg.playbooks || []).find((p) => (p.module || p.key) === m.module);
  if (playbook && (playbook.playbooks || []).length) {
    body.push("## When something breaks here", "");
    for (const entry of playbook.playbooks) {
      body.push(`**${entry.symptom}**`, "", entry.likelyCause, "");
      if ((entry.checkFirst || []).length) {
        body.push(bullets(entry.checkFirst.map((f) => `\`${f.path}\` — ${f.what}`)), "");
      }
      if (entry.fixPattern) body.push(`Fix: ${entry.fixPattern}`, "");
      if (entry.verify) body.push(`Verify: ${entry.verify}`, "");
    }
  }
  if (playbook && (playbook.invariants || []).length) {
    body.push("## Invariants you must not break", "", bullets(playbook.invariants), "");
  }

  const moduleFunctions = (kg.functions || []).filter((f) => f.module === m.module && f.purpose);
  if (moduleFunctions.length) {
    body.push("## Functions in this module", "");
    for (const fn of moduleFunctions.slice(0, 25)) {
      const parts = [`\`${fn.name}(${fn.params || ""})\` \`${fn.location}\` — ${fn.purpose}`];
      if (fn.returns) parts.push(`returns ${fn.returns}`);
      if ((fn.sideEffects || []).length) parts.push(`side effects: ${fn.sideEffects.join("; ")}`);
      if ((fn.throws || []).length) parts.push(`fails when: ${fn.throws.join("; ")}`);
      body.push(`- ${parts.join(" · ")}`);
    }
    body.push("");
  }

  const moduleErrors = (kg.errors || []).filter((e) => e.module === m.module);
  if (moduleErrors.length) {
    body.push("## Errors this module raises", "");
    body.push(
      bullets(
        moduleErrors
          .slice(0, 20)
          .map((e) => `\`${code(e.label)}\` — \`${code(e.path)}:${e.line}\`${e.meaning ? ` · ${cell(e.meaning)}` : ""}`),
      ),
    );
    body.push("");
  }

  const conventions = (kg.overview && kg.overview.conventions) || [];
  if (conventions.length) body.push("## Repository conventions", "", bullets(conventions), "");

  body.push(
    "## Ground rules",
    "",
    "- Every `path:line` above was extracted from this repository's source at a specific commit. If the code disagrees with this document, the code wins — say so rather than trusting the document.",
    "- Never invent an endpoint, field, function or file path. Check before you cite.",
    "- Before changing a function, read its contract: what it returns and what it changes outside itself are what other code depends on.",
    "- After changing anything, re-read the invariants. Passing tests is not the same as not having broken the module.",
    "",
  );

  return front + body.join("\n");
}

function renderFlows(kg) {
  const out = [
    `# Request flows — ${kg.repo.name}`,
    "",
    "Every path below was traced from the call graph: each hop is a real call on",
    "a real line. `file:line` after a function is where it is declared; the arrow",
    "is where it is called from.",
    "",
  ];
  if (!kg.flows || kg.flows.length === 0) {
    return out.concat("_No flows were traced._").join("\n");
  }

  const endpoints = kg.flows.filter((f) => /\s\//.test(f.key));
  const others = kg.flows.filter((f) => !/\s\//.test(f.key));

  const section = (title, flows) => {
    if (flows.length === 0) return;
    out.push(`## ${title}`, "");
    for (const flow of flows) {
      out.push(`### \`${flow.key}\``, "");
      out.push(`Entry: \`${flow.entryPath}:${flow.entryLine}\`${flow.module ? ` · module \`${flow.module}\`` : ""}`);
      if (flow.touches.length) out.push(`Reaches: ${flow.touches.join(" → ")}`);
      out.push("");
      if (flow.steps.length === 0) {
        out.push("_Does its work inline; calls nothing else in this repository._", "");
        continue;
      }
      out.push("```");
      out.push(`${flow.key}   (${flow.entryPath}:${flow.entryLine})`);
      for (const step of flow.steps) {
        const indent = "  ".repeat(step.depth);
        out.push(`${indent}└─ ${step.name}()   ${step.path}:${step.line}   ← called at line ${step.callLine}`);
      }
      out.push("```", "");
      const branches = flow.steps.filter((s) => (s.alsoCalls || []).length);
      if (branches.length) {
        out.push("<details><summary>Other branches from this path</summary>", "");
        for (const step of branches) {
          out.push(`- from \`${step.name}()\`: ${step.alsoCalls.map((b) => `\`${b}\``).join(", ")}`);
        }
        out.push("", "</details>", "");
      }
    }
  };

  section("Endpoints", endpoints);
  section("Jobs, screens and other entry points", others);
  return out.join("\n");
}

function renderPlaybooks(kg) {
  const out = [
    `# Debugging playbooks — ${kg.repo.name}`,
    "",
    "Symptom first. Each entry says what it usually means, which files to open in",
    "which order, what a correct fix looks like here, and how to confirm it.",
    "",
  ];
  if (!kg.playbooks || kg.playbooks.length === 0) {
    return out.concat("_No playbooks have been written yet._").join("\n");
  }

  for (const module of kg.playbooks) {
    out.push(`## ${module.module || module.key}`, "");
    for (const entry of module.playbooks || []) {
      out.push(`### ${entry.symptom}`, "");
      out.push(`**Usually means** ${entry.likelyCause}`, "");
      if ((entry.checkFirst || []).length) {
        out.push("**Open these, in order**", "");
        for (const [i, file] of entry.checkFirst.entries()) {
          out.push(`${i + 1}. \`${file.path}\` — ${file.what}`);
        }
        out.push("");
      }
      if (entry.fixPattern) out.push(`**A correct fix here** ${entry.fixPattern}`, "");
      if (entry.verify) out.push(`**Confirm with** ${entry.verify}`, "");
    }
    if ((module.invariants || []).length) {
      out.push(`### Invariants of ${module.module || module.key}`, "");
      out.push("Breaking one of these breaks the module even if the tests pass.", "");
      out.push(bullets(module.invariants), "");
    }
  }
  return out.join("\n");
}

function renderErrors(kg) {
  const out = [
    `# Error catalogue — ${kg.repo.name}`,
    "",
    "Every failure this codebase can raise, with where it comes from. Paste an",
    "error string from a log and find the line that produced it.",
    "",
  ];
  if (!kg.errors || kg.errors.length === 0) return out.concat("_None found._").join("\n");

  const byModule = new Map();
  for (const e of kg.errors) {
    const key = e.module || "unassigned";
    if (!byModule.has(key)) byModule.set(key, []);
    byModule.get(key).push(e);
  }

  for (const [module, errors] of byModule) {
    out.push(`## ${module}`, "");
    for (const e of errors) {
      // The label is lifted verbatim from someone else's source file. A backtick
      // in it would close the code span and let repository content become prose
      // in a document an agent reads as instructions.
      out.push(`### \`${code(e.label)}\``, "");
      out.push(`- Raised at \`${e.path}:${e.line}\`${e.symbol ? ` in \`${e.symbol}()\`` : ""} (${e.kind})`);
      if (e.meaning) out.push(`- ${e.meaning}`);
      if (e.evidence) out.push(`- Source: \`${e.evidence.replace(/\`/g, "'")}\``);
      out.push("");
    }
  }
  return out.join("\n");
}

function renderFunctions(kg) {
  const out = [
    `# Function contracts — ${kg.repo.name}`,
    "",
    "What each function is for, what it returns, what it changes outside itself,",
    "and how it fails. Ordered by how connected it is.",
    "",
  ];
  const described = (kg.functions || []).filter((f) => f.purpose);
  if (described.length === 0) return out.concat("_No contracts have been written yet._").join("\n");

  const byModule = new Map();
  for (const fn of described) {
    const key = fn.module || fn.layer || "unassigned";
    if (!byModule.has(key)) byModule.set(key, []);
    byModule.get(key).push(fn);
  }

  for (const [module, functions] of byModule) {
    out.push(`## ${module}`, "");
    for (const fn of functions) {
      out.push(`### \`${fn.name}(${fn.params || ""})\``, "");
      out.push(`\`${fn.location}\` · ${fn.kind}${fn.exported ? " · exported" : ""} · called by ${fn.calledBy}, calls ${fn.calls}`, "");
      out.push(fn.purpose, "");
      if (fn.returns) out.push(`**Returns** ${fn.returns}`, "");
      if ((fn.sideEffects || []).length) out.push("**Side effects**", "", bullets(fn.sideEffects), "");
      if ((fn.throws || []).length) out.push("**Fails when**", "", bullets(fn.throws), "");
    }
  }
  return out.join("\n");
}

function renderTests(kg) {
  const out = [`# Test coverage map — ${kg.repo.name}`, ""];
  if (!kg.tests || kg.tests.length === 0) {
    return out.concat("_No tests were found in this repository._").join("\n");
  }
  out.push("Which test file exercises which source file, and what it asserts.", "");
  for (const covered of kg.tests) {
    out.push(`## \`${covered.path}\``, "");
    for (const test of covered.tests) {
      out.push(`- \`${test.path}\``);
      for (const c of test.cases.slice(0, 25)) out.push(`  - ${c}`);
    }
    out.push("");
  }
  return out.join("\n");
}

/** The architecture graph, for anything that wants to draw or traverse it. */
function graphExport(repoId) {
  const files = db
    .prepare(
      `SELECT id, path, ext, loc, layer, role, summary, module, commit_count, churn, heat,
              community, degree, last_change_at
       FROM files WHERE repo_id = ? AND deleted = 0`,
    )
    .all(repoId);
  const edges = db
    .prepare(`SELECT src_id, dst_id, kind, source, weight, how, evidence FROM edges WHERE repo_id = ?`)
    .all(repoId);
  const byId = new Map(files.map((f) => [f.id, f.path]));

  return {
    nodes: files.map((f) => ({
      path: f.path,
      layer: f.layer,
      module: f.module,
      role: f.role,
      summary: f.summary,
      loc: f.loc,
      heat: f.heat,
      churn: f.churn,
      merges: f.commit_count,
      cluster: f.community,
      degree: f.degree,
      lastChangeAt: f.last_change_at,
    })),
    edges: edges
      .map((e) => ({
        from: byId.get(e.src_id),
        to: byId.get(e.dst_id),
        kind: e.kind,
        source: e.source,
        weight: e.weight,
        how: e.how,
        evidence: e.evidence,
      }))
      .filter((e) => e.from && e.to),
  };
}

/** The call graph, symbol by symbol — the machine-readable twin of flows.md. */
function callGraphExport(repoId) {
  const symbols = db
    .prepare(
      `SELECT path, name, kind, line, signature, params, exported, layer, module,
              purpose, returns, side_effects, throws, in_degree, out_degree
       FROM symbols WHERE repo_id = ? AND deleted = 0`,
    )
    .all(repoId);

  const idOf = new Map();
  const rows = db.prepare(`SELECT id, path, name FROM symbols WHERE repo_id = ? AND deleted = 0`).all(repoId);
  for (const r of rows) idOf.set(r.id, `${r.path}::${r.name}`);

  const edges = db
    .prepare(`SELECT src_id, dst_id, kind, line, evidence FROM symbol_edges WHERE repo_id = ?`)
    .all(repoId);

  return {
    nodes: symbols.map((s) => ({
      id: `${s.path}::${s.name}`,
      name: s.name,
      kind: s.kind,
      location: `${s.path}:${s.line}`,
      signature: s.signature,
      params: s.params,
      exported: Boolean(s.exported),
      layer: s.layer,
      module: s.module,
      purpose: s.purpose,
      returns: s.returns,
      sideEffects: JSON.parse(s.side_effects || "[]"),
      throws: JSON.parse(s.throws || "[]"),
      calledBy: s.in_degree,
      calls: s.out_degree,
    })),
    edges: edges
      .map((e) => ({
        from: idOf.get(e.src_id),
        to: idOf.get(e.dst_id),
        kind: e.kind,
        atLine: e.line,
        evidence: e.evidence,
      }))
      .filter((e) => e.from && e.to),
  };
}

/**
 * Write the bundle. `dest` defaults to the app's exports directory; pass a path
 * inside the repo itself to keep the knowledge next to the code it describes.
 */
function exportBundle(repoId, opts = {}) {
  const kg = readKnowledgeGraph(repoId);
  const graph = graphExport(repoId);
  const callGraph = callGraphExport(repoId);
  // Keyed on the repo id as well as the name. `slug(name)` is the last URL
  // segment, so acme/api and beta/api both resolved to "api-knowledge-graph"
  // and the second export overwrote the first.
  const dest =
    opts.dest || path.join(config.exportDir, `${repoId}-${slug(kg.repo.name)}-knowledge-graph`);

  // Clear the generated subtrees first. Exporting into a directory a previous
  // run used left briefs and installed subagents for modules that no longer
  // exist — the stale-documentation failure this bundle is meant to prevent.
  for (const generated of ["modules", "agents"]) {
    fs.rmSync(path.join(dest, generated), { recursive: true, force: true });
  }
  fs.mkdirSync(path.join(dest, "modules"), { recursive: true });
  const written = [];
  const write = (rel, body) => {
    const full = path.join(dest, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, body, "utf8");
    written.push(rel);
  };

  write("CLAUDE.md", renderClaudeMd(kg));
  // Same content under the portable filename, so the bundle works with agent
  // runners that look for AGENTS.md instead.
  write("AGENTS.md", renderClaudeMd(kg));
  write("api-surface.md", renderApiSurface(kg));
  write("data-model.md", renderDataModel(kg));
  write("screens.md", renderScreens(kg));
  write("CHANGELOG.md", renderChangelog(kg));

  // The agent-facing depth: how requests move, what breaks, what each function
  // promises, and what proves it still works.
  write("flows.md", renderFlows(kg));
  write("playbooks.md", renderPlaybooks(kg));
  write("errors.md", renderErrors(kg));
  write("functions.md", renderFunctions(kg));
  write("tests.md", renderTests(kg));

  write("knowledge-graph.json", JSON.stringify(kg, null, 2));
  write("graph.json", JSON.stringify(graph, null, 2));
  write("call-graph.json", JSON.stringify(callGraph, null, 2));

  // Two module names can normalise to the same slug ("API v2" and "api-v2"),
  // and the second silently overwrote the first while the manifest listed both.
  const usedNames = new Set();
  for (const m of kg.modules) {
    let base = slug(m.module) || "module";
    if (usedNames.has(base)) {
      let n = 2;
      while (usedNames.has(`${base}-${n}`)) n++;
      base = `${base}-${n}`;
    }
    usedNames.add(base);
    write(path.join("modules", `${base}.md`), renderModule(m));
    if (opts.agents !== false) write(path.join("agents", `${base}.md`), renderAgent(kg, m));
  }

  write(
    "manifest.json",
    JSON.stringify(
      {
        bundleVersion: BUNDLE_VERSION,
        generator: "RepoDeck",
        repo: kg.repo,
        counts: {
          modules: kg.modules.length,
          endpoints: kg.endpoints.length,
          entities: kg.entities.length,
          screens: kg.screens.length,
          envVars: kg.env.length,
          files: graph.nodes.length,
          fileEdges: graph.edges.length,
          functions: callGraph.nodes.length,
          calls: callGraph.edges.length,
          describedFunctions: (kg.functions || []).filter((f) => f.purpose).length,
          flows: (kg.flows || []).length,
          errors: (kg.errors || []).length,
          playbooks: (kg.playbooks || []).length,
        },
        readingOrder: [
          "CLAUDE.md — start here",
          "flows.md — how a request moves through the system",
          "playbooks.md — symptom → where to look → how to fix",
          "api-surface.md — request and response shapes",
          "functions.md — what each function promises",
          "errors.md — what a given error means",
          "data-model.md, screens.md, tests.md — supporting detail",
          "call-graph.json, knowledge-graph.json — machine-readable everything",
        ],
        files: written,
        exportedAt: new Date().toISOString(),
      },
      null,
      2,
    ),
  );

  return { dest, files: written.length, counts: { ...graph, nodes: graph.nodes.length, edges: graph.edges.length } };
}

module.exports = { exportBundle, graphExport, renderClaudeMd, readKnowledgeGraph };
